apiVersion: v1
kind: Pod
metadata:
  name: link-extractor
spec:
  containers:
  - name: extractor
    image: weblink-extractor:latest
    args: ["-u", "https://news.ycombinator.com"]
    imagePullPolicy: Never
